### ISSUE TITLE
Running YAML E2E tests causes invalid memory address error in the controller

### ISSUE THREAD

**Issue by mgencur** [knative/build#456]
## Expected Behavior

All yaml e2e tests passed when running them.

## Actual Behavior

Initially, the individual yaml files are being processed successfully and builds complete but after some random time the controller throws this error.
`
{"level":"info","logger":"controller.controller","caller":"controller/controller.go:232","msg":"Successfully synced \"build-tests/test-git-tag\"","knative.dev/controller":"controller","knative.dev/controller":"controller"}
E1107 13:59:36.966275       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502q
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/knative/build/pkg/reconciler/build/build.go:161
/go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:225
/go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:234
/go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:159
/go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xedf5ee]

goroutine 115 [running]:
github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  /go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0xfff700, 0x1938a60)
  /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/knative/build/pkg/reconciler/build.(*Reconciler).Reconcile(0xc4200e93b0, 0x1253ce0, 0xc420661500, 0xc4206bb640, 0x1b, 0x3bc2d3200, 0x1949be0)
  /go/src/github.com/knative/build/pkg/reconciler/build/build.go:161 +0x31e
github.com/knative/build/vendor/github.com/knative/pkg/controller.(*Impl).processNextWorkItem.func1(0xc4203baf40, 0xfa0f40, 0xc4206d96a0, 0x0, 0x0)
  /go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:225 +0x328
github.com/knative/build/vendor/github.com/knative/pkg/controller.(*Impl).processNextWorkItem(0xc4203baf40, 0x1)
  /go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:234 +0x6a
github.com/knative/build/vendor/github.com/knative/pkg/controller.(*Impl).Run.func1()
  /go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:159 +0x36
github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4203c1f80)
  /go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4203c1f80, 0x3b9aca00, 0x0, 0xc420990001, 0xc42003e060)
  /go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4203c1f80, 0x3b9aca00, 0xc42003e060)
  /go/src/github.com/knative/build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/knative/build/vendor/github.com/knative/pkg/controller.(*Impl).Run
  /go/src/github.com/knative/build/vendor/github.com/knative/pkg/controller/controller.go:158 +0x115
`
## Steps to Reproduce the Problem

  1. Run yaml e2e tests
  
## Additional Info
I've run these tests on OpenShift (OKD 3.11) but I'm not sure it's related.

**Comment by shashwathi** [comment]
@mgencur : What version of build are you running?

**Comment by mgencur** [comment]
@shashwathi tried HEAD of master branch a few day ago (HEAD=https://github.com/knative/build/commit/3e2db7cb5baf60f70731901258c075e927b89efe)
